-- INSERT INTO burger_list (name) VALUES ('plain');
-- INSERT INTO burger_list (name) VALUES ('cheeseburger');
-- INSERT INTO burger_list (name) VALUES ('double cheeseburger');
-- INSERT INTO burger_list (name) VALUES ('bacon cheeseburger');
-- INSERT INTO burger_list (name) VALUES ('double bacon cheeseburger');
-- INSERT INTO burger_list (name) VALUES ('the heart attack burger');